import 'dotenv/config';

export const GOOGLE_CONFIG = {
  CLIENT_ID: "CLIENT_ID_VALUE",
  CLIENT_SECRET: "CLIENT_SECRET_VALUE",
  ACCESS_TOKEN: "ACCESS_TOKEN_VALUE",
  REFRESH_TOKEN: "REFRESH_TOKEN_VALUE",
  EXPIRY_DATE: 1234567890, // Example timestamp
};
